
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


import math

SQ5 = 5 ** .5
print(SQ5)
PHI = (1+SQ5) /2

def allEvenFibonacciUpTO(limit):
    highestIndexBelowLimit = math.floor(math.log(limit * SQ5) / math.log(PHI))
    print("highest_limit:", highestIndexBelowLimit)

    n = math.floor(highestIndexBelowLimit / 3)
    result = ((PHI ** (3 * n + 3) - 1) / (PHI ** 3 - 1) - ((1 - PHI) ** (3 * n + 3) - 1) / ((1 - PHI) ** 3 - 1)) / SQ5
    return result
    
print(int(allEvenFibonacciUpTO(4e6)))  # // 4613731.999999999


    

